[package]
name = "mapgen"
version = "0.0.1"
authors = ["Michael Chesser"]

[dependencies.bitmap]
git = "https://github.com/quvarxa/bitmap.git"

[dependencies.noise]
git = "https://github.com/bjz/noise-rs"

[dependencies]
rand = "*"
num = "*"
